# -*- mode: org; -*-
#+latex_compiler: xelatex
#+latex_header: \usepackage[AUTO]{polyglossia}
#+latex_header: \setmainfont{Noto Sans}
#+latex_header: \setmonofont{Iosevka}
#+latex_header: \setdefaultlanguage{russian}
#+latex_header: \usepackage{geometry}
#+latex_header: \geometry{left=15mm, top=15mm, right=20mm, bottom=20mm}
* Текст доклада к защите диплома
Здраствуйте уважаемая коммисия, представляю вам доклад к защите
дипломной работы по теме: СИСТЕМА АВТОМАТИЧЕСКОГО УПРАВЛЕНИЯ
БЕСПИЛОТНЫМ ЛЕТАТЕЛЬНЫМ АППАРАТОМ МУЛЬТИРОТОРНОГО ТИПА.

** Актуальность темы
Говоря кратко, разработанное изделие можно назвать одним
словосочетанием — полётный контроллер.  Полётный контроллер нужен
каждому БПЛА мультироторного типа.  При этом полётный контроллер может
не выполнять функции непосредственно автопилота, но всё равно
необходим для того, чтобы преобразовывать поступающий с приёмника
сигнал ШИМ.



** Цель проекта
проектирование конструкции системы автомaтического управления
беспилотным летательным аппаратом мультроторного типа.

** Задачи решенные в данной работе:
Была спроектирована конструкция печатной платы и выполнена
конструкторская документация описывающая её.

А именно:
- Схема электрическая структурная Э1
- Схема электрическая принципиальная Э3
- Чертёж платы (ГУИР.758725.013)
  - 25 В конце децимального номера означает что печатная плата не
    выходит за пределы в 100 мм по длине и ширине.
  - К техническим требованиями можно отнести изготовление платы
    комбинированным позитивным методом.
  - Класс жетскости платы 3
  - Класс точности 3
  - Использовался стеклотекстолит
    - Потому что гетинкс пожароопасен
    - А Фторопласт (ФОФ-4Д) слишком дорог
- Сборочный чертёж изделия
  - Установка элементов по ГОСТ 29137-91

Были также разработаны чертёж основания и общий сборочный чертеж всего
модуля.

Далее будут рассмотрены принцип работы устройства и результаты
моделирования.

** Принцип работы устройства 

*** Сервоприводы

*** Сервоприводы в квадрокоптерах

*** Что делает система автоматического управления БПЛА ?

** На плакате отражены
Результаты моделирования механических воздействия на печатную плату в
SolidWorks Simulation.
