* Технико экономическое обоснование разработки и производства системы автоматического управления беспилотным летательным аппаратом мультироторного типа

** Характеристика нового изделия
Изделие представляет собой двухслойную печатную плату с распаянным на
ней микроконтроллером в DIP корпусе, компонентами и разъёмами.
Область применения данного изделия это беспилотная авиация, а именно
беспилотные мультироторные летательные аппараты, которые в силу своей
специфики, не обладают аэродинамической устойчивостью и потому,
нуждаются в постоянной стабилизации в полёте.  Преимущество этого
изделия является простота его устройства и изготовления,
ремонтопригодность и заменяемость.

** Формирование отпускной цены нового изделия

*** Расчёт затрат по статье «Основные и вспомогательные материалы»
У меня нет каких-то отдельных материалов, типа пластика ABS для
изготовления корпуса, поэтому я пока этот пункт не могу посчитать. Так
как у меня просто нет этого корпуса.

*** Расчёт затрат по статье «Покупные комплектующие изделия, полуфабрикаты»
Для того чтобы это посчитать, надо заполнить перечень элементов и
исходя из перечня элементов считать стоимость каждого компонента и
двухслойной печатной платы.

*** Формирование отпускной цены нового изделия на основе полной себестоимости

*** Методика расчёта полной себестоимости нового изделия методом удельных весов

*** Расчёт полной себестоимости на основе удельных весов

*** Формирование отпускной цены нового изделия на основе себестоимости рассчитанной методом удельных весов

** Расчёт экономического эффекта от производства и реализации новых изделий

** Расчёт инвестиций в производство нового изделия

*** Расчёт инвестиций в прирост собственного оборотного капитала

** Расчёт показателей экономической эффективности в производство нового изделия

