# -*- mode: org; -*-
#+latex_compiler: xelatex
#+latex_header: \usepackage[AUTO]{polyglossia}
#+latex_header: \setmainfont{Noto Sans}
#+latex_header: \setmonofont{Iosevka}
#+latex_header: \setdefaultlanguage{russian}
#+latex_header: \usepackage{geometry}
#+latex_header: \geometry{left=15mm, top=15mm, right=20mm, bottom=20mm}
* Супер серво тестер

Я разработал Супер Серво Тестер престадвленный здесь, потому что дрон
над которым я работаю иногда производит неприятный запах сгоревший электроники
и медного лака, во время тестовых полётов. Мне нужен был инструмент,
чтобы помочь мне диагностировать причины подобных проблем.

В Интеренете, можно найти множество схем сервотестеров для проверки
одного сервопривода. Они позволяют вам проверить, что сервопривод,
только купленный вами, фукнционирует правильно. Тестер представленный
здесь, развивает этот концепт. Вы не только можете проверять до 4
сервоприводов одновременно, но также тестировать электронный
реугулятор хода (ESC -- Electronic Speed Control) или полётный
контроллер вместе с сервоприводами во множетсве конфигураций.

Дрон для которого мне нужен Супер Серво Тестер представлен на рисунке
1 и основан на [[http://www.brokking.net/ymfc-al_main.html][1]].

** Серво Сигналы 101
Напомню, что сервопривод контролируется сигналом ШИМ с частотой
(частотой повторения импульсов) 50 Гц.  Ширина импульса (время когда
сигнал высок) должно быть в промежутке от одной до двух милисекунд,
остальное время сигнал низок. Сервопривод находится в центральном
положении, когда ширина импульса 1,5 милисекунды. Когда импульс
короче, сервопривод поворачивается в одном направлении (например
влево), когда длиннее, то поворачивается в другом направлении
(например вправо).

В типичной полетной системе, пять параметров должны быть проверены:
длина четырёх командных импульсов сервопривода (тяга, крен, тангаж и
рысканье), и напряжение питания.  В случае сложной схемы, например при
разработке полётного контроллера (дрона или другого типа
радиоуправляемой модели) или либого другого импульсного микшера, этот
тестер позволяет увидеть результаты работы микшера.

Обратите внимание, что в остальной части этой статьи термин
«сервопривод» может быть заменен на регулятор хода (ESC) или любое
другое устройство, которое вырабатывает и/или распознает сигналы
сервопривода.

** Характеристики и возможности

Супер Серво Тестер измеряет длительность контролирующих импульсов до
четырёх серво сигналов и предоставляет информацию о качестве
электропитания. Он может быть установлен между приемником
дистанционного управления и сервоприводами, между приёмником и
полётным контроллером дрона, или между полетным контроллером и
сервоприводами. Рисунки 2 - 6 показывают возможные конфигурации.

** Режимы работы
ССТ (Супер Серво Тестер) имеет два режима работы, выбираемых с помощью
ползункового переключателя.

*** Ручной режим:
В этом режиме ССТ генерирует импульсы для четырёх сервоприводов или
для полётного контроллера. Ширина импульсов настраивается четырьмя
потенциометрами. В этом режиме ССТ обеспечивает питанием сервоприводы
или регулятор хода (ESC) и питание модели не должно быть подключено ни
к одному из них. Напряжение питания ССТ должно быть между 7,5В и 12В.


*** Режим ввода:
В этом режиме измерянется длина импульсов приходящих из приёмника или
контроллера. Сигналы также перенаправляются к выводам ССТ для контроля
сервоприводов (или полётного контроллера). В этом режмие, ССТ,
сервпоприводы (или регулятор хода ESC) управляются источником питания
модели. При этом питание не должно привышать 7.49В и ССТ не должен
быть подключен к своему собственному источнику питания.  Также, все
четыре входных канала должны быть подключены, иначе светодиод и
пищалка будут сигнализировать об ошибке.
